# -*- coding: utf-8 -*-
"""AFRIRAZER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjMtqeeAE5dVI3o3D4iZI_BMiaSDbKrx
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import tensorflow as tf
from PIL import Image
import numpy as np
import cv2 as cv
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import imutils
import pickle
import tqdm
from PIL import Image as im
import os

model = tf.keras.models.load_model("/content/drive/My Drive/afrirazer.h5")

cd /content/drive/My Drive/AFRICAN WEARS/Male

import glob
uploaded = './male/1st batch/*.*'

for fn in glob.glob(uploaded):
    #PREDICTING IMAGES    
    path = fn
    file, ext = os.path.splitext(path)
    img = cv.imread(path)
    img = cv.resize(img.copy(),(256,256)) #cv.cvtColor(cv.resize(img.copy(),(224,224)), cv.COLOR_BGRA2RGB)
    
    # print("#"*50)
    # print("Image file: "+fn)
    plt.figure(figsize=(16,8))
    plt.subplot(1,3,1)
    plt.imshow(img)
    
    ### GRUBCUT + PREDICTION ###
    #mask_test, test = cut(img)
    plt.imshow (cv.resize(img,(256,256)))#(cv.cvtColor(cv.resize(img,(224,224)), cv.COLOR_BGRA2RGB))
    test = img.reshape(-1,256,256,3)
    pred = model.predict(test)[0]
    plt.subplot(1,3,2)
    plt.imshow(pred)
    
    ### APPLY PIXEL TRESHOLD FOR MASK ###
    pred_dress = pred.copy()[:,:,1]
    pred_dress[pred_dress>=0.40]=1
    pred_dress[pred_dress<0.40]=0
    real_dress = ((img.copy())*pred_dress[:,:,np.newaxis]).astype('int') #(cv.resize(img.copy(),(224,224))*pred_dress[:,:,np.newaxis]).astype('int')
    real_dress[pred_dress == 0] = (255, 255, 255)
    plt.subplot(1,3,3)
    plt.imshow(real_dress.astype('uint8')) #(cv.cvtColor(real_dress.astype('uint8'), cv.COLOR_BGRA2RGB))
    # print(type(real_dress))
    # print(real_dress)
    real_dress = im.fromarray(real_dress.astype('uint8')) #(cv.cvtColor(real_dress.astype('uint8'), cv.COLOR_BGRA2RGB))
    # real_dress.save(file + ".png","JPEG")

